---
title: |-
  Supporting Information
  Conflicting climate-linked pressures on tropical pelagic seabirds:
output: 
  pdf_document: 
    number_sections: yes
    fig_caption: yes
---

\begin{center}E. Fernando Cagua, April J. Burt, Nancy Bunbury\end{center}

```{r libraries, include = FALSE}
library(magrittr)
library(ggplot2)
library(grid)
library(foreach)
library(dplyr)
library(cowplot)
source("../code/functions.R")
source("../code/plot_helper.R")
```

```{r parameters, include = FALSE}
season_cuts <- seq(as.Date("2009-07-01"), as.Date("2016-07-01"), by = "year")
```


```{r read_data, include = F}
tb <- readRDS('../data/processed/master_df.rds')
```


```{r effort, fig.height= 2, fig.width=7, fig.align="center", message=FALSE, warning=FALSE, echo=FALSE, fig.cap = "Survey effort. Number surveys per month during the study period."}

tb %>%
	gr(month = cut(date, 'month')) %>%
	su(n = n_distinct(date)) %>%
	mu(month = as.Date(month)) %>%
  ggplot(aes(x = month, y = n)) +
  geom_point(fill = "gray25", size = 0.7, shape = 21) +
	geom_step(colour = "gray25") +
	scale_x_date(date_breaks = "4 month",
							 date_labels = "%m/%y", expand = c(0,60)) +
	scale_y_continuous(limits = c(0, 5)) +
  ylab("surveys (month)") +
	theme_fe

```

```{r seasonality-per-islet, echo=FALSE, fig.keep='last', message=FALSE, fig.width=7, fig.height=6, fig.cap = "Seasonality"}
nest_mod <- readRDS('../data/processed/new_nest_models.rds')
library(mgcv)

# generate plot data for the islets
n <- 362/2
islet_fits <- nest_mod$per_islet %>%
	lapply(function(x){
		x %>% lapply(plot, pages = 1, pers = T, n = n, n2 = n)
	})
# extract plot data for the islets
islet_fits <- foreach(i=1:length(islet_fits)) %do% {
	extract_islet_fits(islet_fits[[i]], nest_mod$per_islet[[i]], add_intercept = T) %>%
		lapply(function(y) mu(y, spp_name = names(islet_fits)[i]))
} %>%
	revert_list() %>%
	lapply(function(x){
		dplyr::bind_rows(x[[1]], x[[2]])
	})

# generate plot data for the mean new nest
mean_fits <- nest_mod$mean %>%
	lapply(plot, pages = 1, pers = T, n = n, n2 = n) 
# extract mean plot data
mean_fits <- extract_islet_fits(mean_fits, nest_mod$mean, se = T) %>%
	lapply(function(x){
		x %>% re(spp_name = islet)
	})

var <- 'month'

islet_fits <- islet_fits[var][[1]] 
mean_fits <- mean_fits[var][[1]] 

pm <- ggplot(islet_fits, aes(var, exp(fit), colour = islet)) +
	geom_line(size = 0.5, alpha = 1, show.legend = T) +
	# geom_line(data = mean_fits, aes(y = exp(fit)), 
						# size = 0.75, alpha = 1, show.legend = F) +
	# geom_ribbon(data = mean_fits, aes(ymin = exp(fit-se), ymax = exp(fit+se)),
							# colour = 'transparent', alpha = 0.2) +
	facet_wrap(~spp_name, scales = 'free', ncol = 2) +
	scale_x_continuous(breaks = seq(1, 12, by = 1), labels = month.abb, 
										 name = '', expand = c(0,0)) +
	scale_y_continuous(name = 'number of new nests') +
	scale_colour_brewer(palette = 'Set1') +
	scale_fill_brewer(palette = 'Set1') +
	theme_fe +
	theme(legend.position = 'top')


nest_mod <- readRDS('../data/processed/hatching_success_models.rds')
library(mgcv)

# generate plot data for the islets
n <- 362/2
islet_fits <- nest_mod$per_islet %>%
	lapply(function(x){
		x %>% lapply(plot, pages = 1, pers = T, n = n, n2 = n)
	})
# extract plot data for the islets
islet_fits <- foreach(i=1:length(islet_fits)) %do% {
	extract_islet_fits(islet_fits[[i]], nest_mod$per_islet[[i]], add_intercept = F) %>%
		lapply(function(y) mu(y, spp_name = names(islet_fits)[i]))
} %>%
	revert_list() %>%
	lapply(function(x){
		dplyr::bind_rows(x[[1]], x[[2]])
	})

# generate plot data for the mean new nest
mean_fits <- nest_mod$mean %>%
	lapply(plot, pages = 1, pers = T, n = n, n2 = n) 
# extract mean plot data
mean_fits <- extract_islet_fits(mean_fits, nest_mod$mean, se = T, add_intercept = T) %>%
	lapply(function(x){
		x %>% re(spp_name = islet)
	})

var <- 'month'

islet_fits <- islet_fits[var][[1]]
mean_fits <- mean_fits[var][[1]]

pms <- ggplot(islet_fits, aes(var, colour = islet)) +
	geom_line(aes(group = islet, y = plogis(fit)), size = 0.5, alpha = 1, show.legend = T) +
	# geom_line(data = mean_fits, aes(y = plogis(fit)), 
						# size = 0.75, alpha = 1, show.legend = F) +
	# geom_ribbon(data = mean_fits, aes(ymin = plogis(fit-se), ymax = plogis(fit+se)),
							# colour = 'transparent', alpha = 0.2) +
	facet_wrap(~spp_name, scales = 'free', ncol = 2) +
	scale_x_continuous(breaks = seq(1, 365, by = 30.5), labels = month.abb, 
										 name = '', expand = c(0,0)) +
	scale_y_continuous(name = 'hatching success', labels = scales::percent) +
	scale_colour_brewer(palette = 'Set1') +
	scale_fill_brewer(palette = 'Set1') +
	theme_fe +
	theme(legend.position = 'top')


nest_mod <- readRDS('../data/processed/fledging_success_models.rds')
library(mgcv)

# generate plot data for the islets
n <- 362/2
islet_fits <- nest_mod$per_islet %>%
	lapply(function(x){
		x %>% lapply(plot, pages = 1, pers = T, n = n, n2 = n)
	})
# extract plot data for the islets
islet_fits <- foreach(i=1:length(islet_fits)) %do% {
	extract_islet_fits(islet_fits[[i]], nest_mod$per_islet[[i]], add_intercept = F) %>%
		lapply(function(y) mu(y, spp_name = names(islet_fits)[i]))
} %>%
	revert_list() %>%
	lapply(function(x){
		dplyr::bind_rows(x[[1]], x[[2]])
	})

# generate plot data for the mean new nest
mean_fits <- nest_mod$mean %>%
	lapply(plot, pages = 1, pers = T, n = n, n2 = n) 
# extract mean plot data
mean_fits <- extract_islet_fits(mean_fits, nest_mod$mean, se = T, add_intercept = T) %>%
	lapply(function(x){
		x %>% re(spp_name = islet)
	})

var <- 'month'

islet_fits <- islet_fits[var][[1]]
mean_fits <- mean_fits[var][[1]]

pmsf <- ggplot(islet_fits, aes(var, colour = islet)) +
	geom_line(aes(group = islet, y = plogis(fit)), size = 0.5, alpha = 1, show.legend = T) +
	# geom_line(data = mean_fits, aes(y = plogis(fit)), 
	# 					size = 0.75, alpha = 1, show.legend = F) +
	# geom_ribbon(data = mean_fits, aes(ymin = plogis(fit-se), ymax = plogis(fit+se)),
	# 						colour = 'transparent', alpha = 0.2) +
	facet_wrap(~spp_name, scales = 'free', ncol = 2) +
	scale_x_continuous(breaks = seq(1, 365, by = 30.5), labels = month.abb, 
										 name = '', expand = c(0,0)) +
	scale_y_continuous(name = 'fledging success', labels = scales::percent) +
	scale_colour_brewer(palette = 'Set1') +
	scale_fill_brewer(palette = 'Set1') +
	theme_fe +
	theme(legend.position = 'top')

grobs <- ggplotGrob(pm)$grobs
legend <- grobs[[which(sapply(grobs, function(x) x$name) == "guide-box")]]


plot_grid(legend, pm , pms, pmsf, ncol = 1, labels = c("", "A", "B", "C"), label_size = 10, rel_heights = c(0.3, 1, 1, 1))

```


```{r trends-per-islet, echo=FALSE, fig.keep='last', message=FALSE, fig.width=7, fig.height=6, fig.cap = "Trends"}

nest_mod <- readRDS('../data/processed/new_nest_models.rds')
library(mgcv)

# generate plot data for the islets
n <- 362/2
islet_fits <- nest_mod$per_islet %>%
	lapply(function(x){
		x %>% lapply(plot, pages = 1, pers = T, n = n, n2 = n)
	})
# extract plot data for the islets
islet_fits <- foreach(i=1:length(islet_fits)) %do% {
	extract_islet_fits(islet_fits[[i]], nest_mod$per_islet[[i]], add_intercept = T) %>%
		lapply(function(y) mu(y, spp_name = names(islet_fits)[i]))
} %>%
	revert_list() %>%
	lapply(function(x){
		dplyr::bind_rows(x[[1]], x[[2]])
	})

# generate plot data for the mean new nest
mean_fits <- nest_mod$mean %>%
	lapply(plot, pages = 1, pers = T, n = n, n2 = n) 
# extract mean plot data
mean_fits <- extract_islet_fits(mean_fits, nest_mod$mean, se = T) %>%
	lapply(function(x){
		x %>% re(spp_name = islet)
	})

var <- 'date'

islet_fits <- islet_fits[var][[1]]
mean_fits <- mean_fits[var][[1]]

mean_fits %<>%
	mu(var = as.POSIXct(var, origin = "1970-01-01", tz = "Indian/Mahe"))
islet_fits %<>%
	mu(var = as.POSIXct(var, origin = "1970-01-01", tz = "Indian/Mahe") )

pm <- ggplot(islet_fits, aes(var, exp(fit), colour = islet)) +
	geom_line(aes(group = islet), size = 0.5, alpha = 1, show.legend = T) +
	# geom_line(data = mean_fits, aes(y = exp(fit)), 
						# size = 0.75, alpha = 1, show.legend = F) +
	# geom_ribbon(data = mean_fits, aes(ymin = exp(fit-se), ymax = exp(fit+se)),
							# colour = 'transparent', alpha = 0.2) +
	facet_wrap(~spp_name, scales = 'free', ncol = 2) +
	scale_x_datetime(name = '', expand = c(0,0)) +
	scale_y_continuous(name = 'number of new nests') +
	scale_colour_brewer(palette = 'Set1') +
	scale_fill_brewer(palette = 'Set1') +
	theme_fe +
	theme(legend.position = 'top')



nest_mod <- readRDS('../data/processed/hatching_success_models.rds')
library(mgcv)

# generate plot data for the islets
n <- 362/2
islet_fits <- nest_mod$per_islet %>%
	lapply(function(x){
		x %>% lapply(plot, pages = 1, pers = T, n = n, n2 = n)
	})
# extract plot data for the islets
islet_fits <- foreach(i=1:length(islet_fits)) %do% {
	extract_islet_fits(islet_fits[[i]], nest_mod$per_islet[[i]], add_intercept = F) %>%
		lapply(function(y) mu(y, spp_name = names(islet_fits)[i]))
} %>%
	revert_list() %>%
	lapply(function(x){
		dplyr::bind_rows(x[[1]], x[[2]])
	})

# generate plot data for the mean new nest
mean_fits <- nest_mod$mean %>%
	lapply(plot, pages = 1, pers = T, n = n, n2 = n) 
# extract mean plot data
mean_fits <- extract_islet_fits(mean_fits, nest_mod$mean, se = T, add_intercept = T) %>%
	lapply(function(x){
		x %>% re(spp_name = islet)
	})

var <- 'date'

islet_fits <- islet_fits[var][[1]]
mean_fits <- mean_fits[var][[1]]

mean_fits %<>%
	mu(var = as.POSIXct(var, origin = "1970-01-01", tz = "Indian/Mahe"))
islet_fits %<>%
	mu(var = as.POSIXct(var, origin = "1970-01-01", tz = "Indian/Mahe") )

pms <- ggplot(islet_fits, aes(var, colour = islet)) +
	geom_line(aes(group = islet, y = plogis(fit)), size = 0.5, alpha = 1, show.legend = T) +
	# geom_line(data = mean_fits, aes(y = plogis(fit)), 
	# 					# size = 0.75, alpha = 1, show.legend = F) +
	# geom_ribbon(data = mean_fits, aes(ymin = plogis(fit-se), ymax = plogis(fit+se)),
							# colour = 'transparent', alpha = 0.2) +
	facet_wrap(~spp_name, scales = 'free', ncol = 2) +
	scale_x_datetime(name = '', expand = c(0,0)) +
	scale_y_continuous(name = 'hatching success', labels = scales::percent) +
	scale_colour_brewer(palette = 'Set1') +
	scale_fill_brewer(palette = 'Set1') +
	theme_fe +
	theme(legend.position = 'top')



nest_mod <- readRDS('../data/processed/fledging_success_models.rds')
library(mgcv)

# generate plot data for the islets
n <- 362/2
islet_fits <- nest_mod$per_islet %>%
	lapply(function(x){
		x %>% lapply(plot, pages = 1, pers = T, n = n, n2 = n)
	})
# extract plot data for the islets
islet_fits <- foreach(i=1:length(islet_fits)) %do% {
	extract_islet_fits(islet_fits[[i]], nest_mod$per_islet[[i]], add_intercept = F) %>%
		lapply(function(y) mu(y, spp_name = names(islet_fits)[i]))
} %>%
	revert_list() %>%
	lapply(function(x){
		dplyr::bind_rows(x[[1]], x[[2]])
	})

# generate plot data for the mean new nest
mean_fits <- nest_mod$mean %>%
	lapply(plot, pages = 1, pers = T, n = n, n2 = n) 
# extract mean plot data
mean_fits <- extract_islet_fits(mean_fits, nest_mod$mean, se = T, add_intercept = T) %>%
	lapply(function(x){
		x %>% re(spp_name = islet)
	})

var <- 'date'

islet_fits <- islet_fits[var][[1]]
mean_fits <- mean_fits[var][[1]]

mean_fits %<>%
	mu(var = as.POSIXct(var, origin = "1970-01-01", tz = "Indian/Mahe"))
islet_fits %<>%
	mu(var = as.POSIXct(var, origin = "1970-01-01", tz = "Indian/Mahe") )

pmsf <- ggplot(islet_fits, aes(var, colour = islet)) +
	geom_line(aes(group = islet, y = plogis(fit)), size = 0.5, alpha = 1, show.legend = T) +
	# geom_line(data = mean_fits, aes(y = plogis(fit)), 
						# size = 0.75, alpha = 1, show.legend = F) +
	# geom_ribbon(data = mean_fits, aes(ymin = plogis(fit-se), ymax = plogis(fit+se)),
							# colour = 'transparent', alpha = 0.2) +
	facet_wrap(~spp_name, scales = 'free', ncol = 2) +
	scale_x_datetime(name = '', expand = c(0,0)) +
	scale_y_continuous(name = 'fledging success', labels = scales::percent) +
	scale_colour_brewer(palette = 'Set1') +
	scale_fill_brewer(palette = 'Set1') +
	theme_fe +
	theme(legend.position = 'top')

cowplot::plot_grid(pm, pms, pmsf, ncol = 1, labels = c("A", "B", "C"), label_size = 10)
```